parameters:
  lch.media.uploader.class: Lch\MediaBundle\Loader\MediaUploader
  lch.media.downloader.class: Lch\MediaBundle\Loader\MediaDownloader
  lch.media.manager.class: Lch\MediaBundle\Manager\MediaManager
  lch.media.pdf.manager.class: Lch\MediaBundle\Manager\PdfManager
  lch.media.twig.extension.class: Lch\MediaBundle\Twig\MediaExtension
  lch.media.twig.runtime.class: Lch\MediaBundle\Twig\MediaRuntime
  lch.media.subscriber.class: Lch\MediaBundle\Listener\MediaSubscriber

  lch.media.image.manager.class: Lch\MediaBundle\Manager\ImageManager
  lch.media.image.regenerate_thumbnails.command.class: Lch\MediaBundle\Command\RegenerateImageThumbnailsCommand
  lch.media.image.subscriber.class: Lch\MediaBundle\Listener\ImageSubscriber

  lch.media.pdf.regenerate_thumbnails.command.class: Lch\MediaBundle\Command\RegeneratePdfThumbnailsCommand
  lch.media.pdf.subscriber.class: Lch\MediaBundle\Listener\PdfSubscriber

  lch.media.service.class_analyzer.class: Lch\MediaBundle\Service\ClassAnalyzer

  lch.media.types:
      image:
        form:       'Lch\MediaBundle\Form\ImageType'
        add_view:   'LchMediaBundle:Image/fragments:add.html.twig'
        edit_view:   'LchMediaBundle:Image/fragments:edit.html.twig'
        thumbnail_view: 'LchMediaBundle:Image/fragments:thumbnail.html.twig'
        list_item_view: 'LchMediaBundle:Image/fragments:list.item.html.twig'
        extensions: ['jpg', 'jpeg', 'png', 'gif']
        thumbnail_sizes:
          list_thumbnail:
            width: 50
            height: 50
            strategy: resize

      pdf:
        form:       'Lch\MediaBundle\Form\PdfType'
        add_view:   'LchMediaBundle:Pdf/fragments:add.html.twig'
        thumbnail_view: 'LchMediaBundle:Pdf/fragments:thumbnail.html.twig'
        list_item_view: 'LchMediaBundle:Pdf/fragments:list.item.html.twig'
        extensions: ['pdf']

  lch.media.fallback_file_path: ~ # par default null donc aucun fichier par default si le fichier n'existe pas


services:
  lch.media.service.class_analyzer:
    class: '%lch.media.service.class_analyzer.class%'
    public: false

  lch.media.uploader:
    class: '%lch.media.uploader.class%'
    arguments: [ '@lch.media.service.class_analyzer', '%kernel.project_dir%', '%lch_media.root_folder%' ]
    public: true
    lazy: true

  lch.media.downloader:
    class: '%lch.media.downloader.class%'
    arguments: [ '%kernel.project_dir%', '%lch_media.root_folder%' ]
    public: true
    lazy: true

  lch.media.form:
    class: Lch\MediaBundle\Form\AddOrChooseMediaType
    arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher", '%lch.media.types%' ]
    tags:
      - { name: form.type }
    lazy: true

  lch.media.multiple.form:
    class: Lch\MediaBundle\Form\AddOrChooseMultipleMediasType
    arguments: [ "@doctrine.orm.entity_manager", "@event_dispatcher", '%lch.media.types%' ]
    tags:
      - { name: form.type }
    lazy: true

  lch.media.twig.extension:
    class: "%lch.media.twig.extension.class%"
    tags:
      - { name: twig.extension }
    lazy: true

  lch.media.twig.extension.runtime:
    class: "%lch.media.twig.runtime.class%"
    arguments: [ '@lch.media.manager', '@twig', '%lch.media.types%' ]
    tags:
      - { name: twig.runtime }
    lazy: true

  lch.media.manager:
    class: '%lch.media.manager.class%'
    arguments: [ '@lch.media.uploader', '@doctrine.orm.entity_manager', '@event_dispatcher', '%lch.media.types%' ]
    public: true
    lazy: true

  lch.media.image.manager:
    class: '%lch.media.image.manager.class%'
    arguments: [ '@lch.media.manager','@lch.media.uploader' ]
    public: true
    lazy: true

  lch.media.pdf.manager:
    class: '%lch.media.pdf.manager.class%'
    arguments: [ '@lch.media.manager' ]
    public: true
    lazy: true

  lch.media.extension.validator:
    class: Lch\MediaBundle\Validator\Constraints\HasAllowedFileExtensionValidator
    arguments: [ '%kernel.project_dir%', '@lch.media.manager' ]
    tags:
      - { name: validator.constraint_validator, alias: alias_name }
    lazy: true

  lch.media.weight.validator:
    class: Lch\MediaBundle\Validator\Constraints\MediaWeightValidator
    arguments: [ '%kernel.project_dir%', '@lch.media.manager' ]
    tags:
      - { name: validator.constraint_validator, alias: alias_name }
    lazy: true

  lch.media.image.size.validator:
    class: Lch\MediaBundle\Validator\Constraints\ImageSizeValidator
    arguments: [ '@session', '@translator' ]
    tags:
      - { name: validator.constraint_validator, alias: alias_name }
    lazy: true

  lch.media.subscriber:
    class: '%lch.media.subscriber.class%'
    arguments: ['@lch.media.uploader','@lch.media.pdf.manager','%kernel.project_dir%']
    tags:
      - { name: kernel.event_subscriber }
    public: true
    lazy: true

  lch.media.image.subscriber:
    class: '%lch.media.image.subscriber.class%'
    arguments: ['@lch.media.image.manager', '%kernel.project_dir%']
    tags:
      - { name: kernel.event_subscriber }
    public: true
    lazy: true

  lch.media.image.regenerate_thumbnail.command:
    class: '%lch.media.image.regenerate_thumbnails.command.class%'
    arguments: ['@doctrine.orm.entity_manager', '@lch.media.image.manager', '%lch.media.types%']
    tags:
      - { name: console.command }
    public: true
    lazy: true

  lch.media.pdf.regenerate_thumbnail.command:
    class: '%lch.media.pdf.regenerate_thumbnails.command.class%'
    arguments: ['@doctrine.orm.entity_manager', '@lch.media.pdf.manager', '%lch.media.types%']
    tags:
      - { name: console.command }
    public: true
    lazy: true

  lch.media.doctrine.listener:
    class: Lch\MediaBundle\Listener\DoctrineMediaListener
    arguments: ['@lch.media.uploader', '%kernel.project_dir%',  '%lch.media.fallback_file_path%']
    tags:
        - { name: doctrine.event_listener, event: postLoad }
        - { name: doctrine.event_listener, event: postPersist }
    lazy: true

  lch.media.pdf.subscriber:
    class: '%lch.media.pdf.subscriber.class%'
    arguments: ['@lch.media.manager']
    tags:
      - { name: kernel.event_subscriber }
    public: true
    lazy: true