<?php

namespace Lch\MediaBundle\Repository;

/**
 * PdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfRepository extends \Doctrine\ORM\EntityRepository
{
}
